//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Checkout
    {
        public int CheckoutID { get; set; }
        public int BookID { get; set; }
        public int PatronID { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual Patron Patron { get; set; }
    }
}
